### PR TITLE
Feature5

### PR DESCRIPTION
**Pull request by haraphat01**
This is the complete project on the fifth milestone.

What does this include?

- The working App component
- The Button Component 
- The ButtonPanel Component
The codes have been pushed to Heroku.

### CODE REVIEW

**Review by Torres-ssf — CHANGES_REQUESTED** [review]
### Changes required :muscle: 
Hi @haraphat01 :hand: 
Awesome job on this milestone so far :clap: 
But we need to make some changes before moving on.

- [ ] The live link at your README file it's a broken link. We need to fix it and provide the right link.

- [ ] Right now the division feature it's not working properly.
err1
Also, remember that the app should handle (not allow) the division by 0.

- [ ] If the dot it's not present the number 0 should not be allowed to be at the beginning of the operation.
err2

Happy coding :computer: 
**Sérgio Torres**

**Comment by haraphat01** [comment]
Fixed the Heroku and the division sign issue

**Review by addod19 — CHANGES_REQUESTED** [review]
## Status: Require changes :recycle: :traffic_light: 

Hi @haraphat01, great job implementing some of the comments outlined by the previous TSE :+1: The live link is fixed, but we need to update it in the README file. Let us also address the comments below:
- The "dot" `.` operator is not working as expected, it should appear only once instead of multiple times
dot
- The link in the README is broken, kindly fix it :fireworks: 

Once these are resolved, kindly submit another code review :slightly_smiling_face: 
_Happy coding_ :man_technologist: 
[Daniel Larbi Addo](linkedin.com/in/daniel-larbi-addo/)

**Review by MuriloRoque — APPROVED** [review]
## Status: Approved :green_circle: 

### Hello @haraphat01 :wave: 

### Thank you for making all of the requested changes. Your project is approved :clap: :clap: :clap: 

### You may merge, good luck with your next projects :rocket: 

Murilo Roque Paiva da Silva

- Github: [@muriloroque](https://github.com/MuriloRoque)
- Linkedin: [MuriloRoque](https://www.linkedin.com/in/murilo-roque-b1268741/)

[Twitter Follow](https://twitter.com/MuriloRoquePai1)

**Pull request merged**
