### PR TITLE
Calculator

### PR DESCRIPTION
**Pull request by haraphat01**
This is the first milestone for the calculator project, what did I do in this milestone?

- Created the React App
- Added the linters
- Added Props Checker

### CODE REVIEW

**Review by addod19 — CHANGES_REQUESTED** [review]
## Status: Require changes :recycle: :traffic_light: 

Hi @haraphat01, great job on this project :smile: The README looks good, the PR has a title and a short description :100: However, there are a few missing requirements that need to be addressed. Kindly check the comments below: :+1: 
- Kindly delete unnecessary files or assets such as the React SVG logo, and files that are not needed for the project
- Kindly add big.js to our package.json file
- Kindly add a live version of the app to our README file

[Optional]
- Our README file must also include instructions about how to clone the project and run it locally :1st_place_medal: 

Once these are fixed, kindly submit another code review request :smile: 
_Happy coding_ :man_technologist: 
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo/)

**Review by addod19 — CHANGES_REQUESTED** [review]
## Status: Require changes :recycle: :traffic_light: 

Hi @haraphat01, good job :+1: We implemented some of the comments in the review :slightly_smiling_face: The unnecessary files have been deleted, the live link has been added to the README file but our app is not deployed. This needs to be fixed :smile: Let us fix the following comments:
- Add big.js to our package.json file
- Our App must be deployed, we currently have a live link that is on heroku

Once these are resolved :+1: Kindly submit another code review request :smile: 
_Happy coding_ :man_technologist: 
[Daniel Larbi Addo](linkedin.com/in/daniel-larbi-addo/)

**Comment by haraphat01** [comment]
big

I don't understand your message, the big.js is already added to the package.json, while I've also deployed it to Heroku too.
heroku

**Review by addod19 — APPROVED** [review]
## Status: Approved :trophy: :balloon: 

Hi @haraphat01, congratulations :fireworks: All requirements have been resolved :100: 

Go ahead and merge into development and continue with the next milestone :fireworks: 
_Happy coding_ :man_technologist: 
[Daniel Larbi Addo](linkedin.com/in/daniel-larbi-addo/)

**Pull request merged**
